name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project with debug output
        working-directory: app
        run: |
          ./gradlew clean build --stacktrace --info

      - name: Generate coverage report
        working-directory: app
        run: |
          ./gradlew jacocoTestReport --stacktrace --info

      - name: List JaCoCo reports
        working-directory: app
        run: |
          echo "Checking JaCoCo output"
          find build/reports -type f || echo "No reports found"

      - name: Show Sonar properties
        working-directory: app
        run: |
          echo "SONAR_TOKEN is set: ${SONAR_TOKEN:+yes}"
          grep "sonar" build.gradle.kts || echo "No sonar config in build.gradle.kts"

      - name: Run SonarCloud analysis with debug
        working-directory: app
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonar --stacktrace --info

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: |
            app/build/reports
            app/build/*.log